# Generated by Django 4.0.2 on 2022-02-23 16:41

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Treść')),
                ('published', models.BooleanField(default=False, verbose_name='Opublikowany')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, common.models.CheckAgeMixin),
        ),
    ]
